### ISSUE TITLE
StringValidator Min_length and Max_length Throws error when None is passed as input

### ISSUE THREAD

**Issue by nagesh-chowdaiah** [uzumaxy/pyvalid#55]
Traceback (most recent call last):
  File "C:/Users/40102447/oss/pyvalid/example.py", line 61, in <module>
    register_users(new_user, "Nandan")
  File "C:\Users\40102447\oss\pyvalid\pyvalid\__accepts.py", line 86, in decorator_wrapper
    self.__validate_args(func, func_args, func_kwargs)
  File "C:\Users\40102447\oss\pyvalid\pyvalid\__accepts.py", line 181, in __validate_args
    is_valid = allowed_val(value)
  File "C:\Users\40102447\oss\pyvalid\pyvalid\validators\__schema.py", line 79, in __call__
    valid_args = self._check(val)
  File "C:\Users\40102447\oss\pyvalid\pyvalid\validators\__schema.py", line 94, in _check
    valid = checker_func(value, *checker_args)
  File "C:\Users\40102447\oss\pyvalid\pyvalid\validators\__string.py", line 19, in max_len_checker
    return len(val) <= max_len
TypeError: object of type 'NoneType' has no len()

**Comment by uzumaxy** [comment]
Hey @nagesh-chowdaiah ,
Could you please provide a bit more details regarding Python version, which you've used for reproducing this issue? Recently I've added a few new unittest checks for the None value: #60 All the unittests were passed without any errors. So this issue may be version-specific.
Thanks!

**Comment by nagesh-chowdaiah** [comment]
@uzumaxy 
```
from pyvalid.validators import SchemaValidator, StringValidator, NumberValidator
from pyvalid import accepts

user_schema = SchemaValidator({
    'name': StringValidator(re_pattern=r'^[A-Za-z]+\s?[A-Za-z]+\s?[A-Za-z]+$'),
    'birthyear': NumberValidator(min_val=1990, max_val=2010),
    'rating': float,
    # 'bio': [StringValidator(max_len=2048), None]
})

new_schema = SchemaValidator({
            'name': StringValidator(re_pattern=r'^[A-Za-z]+\s?[A-Za-z]+\s?[A-Za-z]+$'),
            'birthyear': NumberValidator(min_val=1890, max_val=2020),
            'rating': float,
            'bio': StringValidator(min_len=1),
            'new_data': user_schema
        })


# So we can use schemas for `@accepts` and `@returns`
# @accepts(new_user=user_schema)
# def register_user(new_user):
#     # some logic here
#     pass


# Or we can call them directly to validate some data
# user_schema({
#     'name': 'Max',
#     'birthyear': -42,  # will cause a validator error
#     'bio': None,
#     'rating': 8.0
#     # the `address` attribute is missing, what will cause another error even if we fix `birthyear`
# })

old_user = {
    'name': 'Nagesh',
    'birthyear': 1994,  # will cause a validator error
    # 'bio': None,
    'rating': 8.0
}

@accepts(new_user=new_schema, X=StringValidator(re_pattern=r'^[A-Za-z]+\s?[A-Za-z]+\s?[A-Za-z]+$'))
def register_users(new_user, X):
    # some logic here
    pass

new_user = {
    'name': 'Nandeesh',
    'birthyear': 2020,  # will cause a validator error
    'bio': None,
    'rating': 8.0,
    'new_data': old_user
    # the `address` attribute is missing, what will cause another error even if we fix `birthyear`
}

register_users(new_user, "Nandan")
```
I was working on SchemaValidator and I used StringValidator for one of the params. Then i found this error
you can run the code on branch 41_SchemaValidator

**Comment by uzumaxy** [comment]
Hey @nagesh-chowdaiah ,
Thanks for providing an example! I checked this issue and I can say for sure, that we don't need to check input values for the `None` value. We already have the same verification in the `__call__` method for all out validators:
```python
# NumberValidator (pyvalid/validators/__number.py)
def __call__(self, val):
        valid = isinstance(val, NumberValidator.number_types) and self._check(val)
        return valid

# StringValidator (pyvalid/validators/__string.py)
def __call__(self, val):
        valid = isinstance(val, str) and self._check(val)
        return valid

# IterableValidator (pyvalid/validators/__iterable.py)
def __call__(self, val):
        is_iterable = isinstance(val, IterableValidator.iterable_types)
        valid = is_iterable and self._check(val)
        return valid

# ...
```

So when we're calling one of the validators, we also execute the `__call__` function, which checks the type of the input value and then switches to all the `self.__checkers` by executing the `self._check` method. So we never will accept the wrong type in the `StringValidator.min_len_checker` or `StringValidator.max_len_checker` since the `__call__` function won't allow it.

The problem was inside the `SchemaValidator` class. Here we called `self.__checkers` of other validators directly, without the  `__call__` function. So, we were able to skip the validation.

I fixed this issue and simplified the `SchemaValidator` class for a bit (without losing in the functionality) in [this](https://github.com/uzumaxy/pyvalid/commit/d9606a9b4f0adac864be641b02243b0a6b8979d0) commit.  All the changes are available on the [develop branch](https://github.com/uzumaxy/pyvalid/settings/branches), feel free to check it on your own.

The example, which you've provided shouldn't throw an error related to the None value anymore. Please let me know if you will have any question.

**Comment by nagesh-chowdaiah** [comment]
@uzumaxy Amazing changes
